FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./
RUN npm ci

COPY . .

ENV NODE_ENV=development
ENV NODE_OPTIONS="--max-old-space-size=1024"

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
